// autogenerated file
const levels = [
  {
    id: 0,
    walls: [
      [
        { x: 416, y: 768 },
        { x: 416, y: 288 },
        { x: 320, y: 288 },
        { x: 320, y: 160 },
        { x: 576, y: 160 },
        { x: 576, y: 288 },
        { x: 480, y: 288 },
        { x: 480, y: 768 },
        { x: 416, y: 768 }
      ]
    ],
    doors: [
      {
        open: false,
        name: "door1",
        polygon: [{ x: 416, y: 288 }, { x: 480, y: 288 }, { x: 416, y: 288 }]
      }
    ],
    switches: [
      {
        target: "door1",
        type: "momentary",
        x: 448,
        y: 480,
        name: "switch1",
        targets: ["door1"],
        pressed: 0
      }
    ],
    start: { x: 448, y: 736 },
    end: { x: 448, y: 224 }
  },
  {
    id: 1,
    walls: [
      [
        { x: 288, y: 960 },
        { x: 288, y: 800 },
        { x: 416, y: 800 },
        { x: 416, y: 832 },
        { x: 448, y: 832 },
        { x: 448, y: 768 },
        { x: 320, y: 768 },
        { x: 320, y: 576 },
        { x: 448, y: 576 },
        { x: 448, y: 352 },
        { x: 416, y: 352 },
        { x: 416, y: 224 },
        { x: 544, y: 224 },
        { x: 544, y: 352 },
        { x: 512, y: 352 },
        { x: 512, y: 352 },
        { x: 512, y: 480 },
        { x: 736, y: 480 },
        { x: 736, y: 608 },
        { x: 832, y: 608 },
        { x: 832, y: 736 },
        { x: 576, y: 736 },
        { x: 576, y: 608 },
        { x: 672, y: 608 },
        { x: 672, y: 544 },
        { x: 512, y: 544 },
        { x: 512, y: 640 },
        { x: 384, y: 640 },
        { x: 384, y: 704 },
        { x: 512, y: 704 },
        { x: 512, y: 896 },
        { x: 416, y: 896 },
        { x: 416, y: 960 },
        { x: 288, y: 960 }
      ]
    ],
    doors: [
      {
        open: false,
        name: "door2",
        polygon: [{ x: 448, y: 352 }, { x: 512, y: 352 }, { x: 448, y: 352 }]
      },
      {
        open: false,
        name: "door1",
        polygon: [
          { x: 448, y: 416 },
          { x: 448, y: 416 },
          { x: 512, y: 416 },
          { x: 448, y: 416 }
        ]
      }
    ],
    switches: [
      {
        target: "door1",
        type: "momentary",
        x: 768,
        y: 672,
        name: "switch1",
        targets: ["door1"],
        pressed: 0
      },
      {
        target: "door2",
        type: "momentary",
        x: 640,
        y: 672,
        name: "switch2",
        targets: ["door2"],
        pressed: 0
      }
    ],
    start: { x: 352, y: 896 },
    end: { x: 480, y: 288 }
  },
  {
    id: 2,
    walls: [
      [
        { x: 448, y: 960 },
        { x: 448, y: 736 },
        { x: 128, y: 736 },
        { x: 128, y: 384 },
        { x: 416, y: 384 },
        { x: 416, y: 640 },
        { x: 192, y: 640 },
        { x: 192, y: 672 },
        { x: 448, y: 672 },
        { x: 448, y: 352 },
        { x: 320, y: 352 },
        { x: 320, y: 224 },
        { x: 640, y: 224 },
        { x: 640, y: 352 },
        { x: 512, y: 352 },
        { x: 512, y: 672 },
        { x: 800, y: 672 },
        { x: 800, y: 736 },
        { x: 512, y: 736 },
        { x: 512, y: 960 },
        { x: 448, y: 960 }
      ]
    ],
    doors: [
      {
        open: false,
        name: "door2",
        polygon: [{ x: 448, y: 352 }, { x: 512, y: 352 }, { x: 448, y: 352 }]
      },
      {
        open: false,
        name: "door1",
        polygon: [{ x: 448, y: 672 }, { x: 448, y: 736 }, { x: 448, y: 672 }]
      }
    ],
    switches: [
      {
        target: "door2",
        type: "momentary",
        x: 352,
        y: 512,
        name: "switch",
        targets: ["door2"],
        pressed: 0
      },
      {
        target: "door1",
        type: "toggle",
        x: 769,
        y: 702,
        name: "switch1",
        targets: ["door1"],
        pressed: 0
      }
    ],
    start: { x: 480, y: 928 },
    end: { x: 480, y: 288 }
  },
  {
    id: 3,
    walls: [
      [
        { x: 416, y: 960 },
        { x: 416, y: 288 },
        { x: 320, y: 288 },
        { x: 320, y: 672 },
        { x: 384, y: 672 },
        { x: 384, y: 800 },
        { x: 256, y: 800 },
        { x: 256, y: 224 },
        { x: 416, y: 224 },
        { x: 416, y: 96 },
        { x: 192, y: 96 },
        { x: 192, y: 832 },
        { x: 384, y: 832 },
        { x: 384, y: 960 },
        { x: 128, y: 960 },
        { x: 128, y: 32 },
        { x: 480, y: 32 },
        { x: 480, y: 224 },
        { x: 640, y: 224 },
        { x: 640, y: 800 },
        { x: 512, y: 800 },
        { x: 512, y: 672 },
        { x: 576, y: 672 },
        { x: 576, y: 288 },
        { x: 480, y: 288 },
        { x: 480, y: 960 },
        { x: 416, y: 960 }
      ]
    ],
    doors: [
      {
        open: false,
        test: 123,
        name: "door1",
        polygon: [{ x: 416, y: 416 }, { x: 480, y: 416 }, { x: 416, y: 416 }]
      },
      {
        open: false,
        name: "door1",
        polygon: [{ x: 416, y: 512 }, { x: 480, y: 512 }, { x: 416, y: 512 }]
      },
      {
        open: false,
        name: "door1",
        polygon: [{ x: 576, y: 576 }, { x: 640, y: 576 }, { x: 576, y: 576 }]
      }
    ],
    switches: [
      {
        target: "door1",
        type: "momentary",
        x: 448,
        y: 480,
        name: "switch1",
        targets: ["door1"],
        pressed: 0
      },
      {
        target: "door1",
        type: "momentary",
        x: 320,
        y: 736,
        name: "switch1",
        targets: ["door1"],
        pressed: 0
      },
      {
        target: "door1",
        type: "momentary",
        x: 448,
        y: 576,
        name: "switch1",
        targets: ["door1"],
        pressed: 0
      }
    ],
    start: { x: 448, y: 736 },
    end: { x: 576, y: 736 }
  }
];
